### ISSUE TITLE
Enhance OpenHAB compatibility without colons

### ISSUE THREAD

**Issue by codegrau** [andrewjfreyer/presence#16]
While this is an incredibly awesome script I do have a hard time to use these MQTT messages in openHAB because of the colons in topic. 

OpenHAB uses colons in MQTT binding and so mac addresses with lots of colons don’t work:

Item myItem {mqtt="<direction>[<broker>:<topic>:<type>:<transformer>], <direction>[<broker>:<topic>:<type>:<transformation>], ..."} 

Would be great if there would be an option to change the topic title to not use colons or just bring that piece of information into payload.

**Comment by codegrau** [comment]
Can be solved by escaping the colons in MAC address in openHAB with \\:

**Comment by andrewjfreyer** [comment]
If you check the monitor project, I added an express feature (flag `-f`) for formatting the MQTT topic without colons.
