### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by danielaradu2016** [andrewjfreyer/presence#18]
I have a MiBand 3 Xiaomi and i want to use it with your program but i have this issue:`location/owner/habitacion1/EC:89:64:02:CC:54 {"confidence":"0","name":"Invalid device: No such device","scan_duration_ms":"5071","timestamp":"Sun Sep 09 2018 08:52:17 GMT+0200 (CEST)"}
`.
in my mqtt i have this:
`mqtt_address="my broker"
mqtt_port="1883"
mqtt_user="myuser"
mqtt_password="mypassword"
mqtt_topicpath="location"
mqtt_room="habitacion1"`

and in my  owner_devices i have: 

 `EC:89:64:02:CC:54  #mywatch`
 
in Hassio sensor i have:
`- platform: mqtt
  state_topic: 'location/owner/habitacion1/EC:89:64:02:CC:54'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Habitacion' ` 
but my sensor.habitacion he still 0% and i was in my room with my watch.

Can you help me plz? sorry for my language.i leave in spain.

**Comment by cgtobi** [comment]
Your MiBand is probably paired to your phone. The way Bluetooth is designed you can have only one connection at a time. If you turn Bluetooth off on your phone you should see it being detected. This is probably not what you intended.

**Comment by andrewjfreyer** [comment]
sugiero que pruebes mi otro script llamado 'monitor.sh' ([https://www.guthub.com/andrewjfreyer/monitor](aqui)) pero creo que el otro comentario también es correcto. 

parece que varias personas tienen este dispositivo, tal vez debería comprar uno y comenzar a probar....

**Comment by danielaradu2016** [comment]
Hy.Thanks a lot for you answerd. i just unpair with my ipad and i shutdown the bluetooth from ipad but i have this   :  `location/owner/habitacion1/ec:89:64:02:cc:54 {"confidence":"0","name":"Unknown","scan_duration_ms":"5075","timestamp":"Sun Sep 09 2018 16:05:32 GMT+0200 (CEST)"}`. i change EC to ec but still nothing.
i buy it only for homeassiatnt. but i see that he dont want connect with him.
should be that MiBand 3 dont work with this.
Can you help me with one informacion?what smart watch did work with your program.?i wish connect my watch no my phone. Thx a lot

**Comment by danielaradu2016** [comment]
andrewjfreyer  muchas gracias. ahora mismo estoy intentando con el monitor.Muchas gracias.Tengo muchas problemas con el pi zero sobre¨¨ segmentation fault¨¨ pero lo intentare.Me podrias ayudar sobre un reloj inteligente que funcionara con Hassio y room presence¿¿
estoy un poco delusionada porque me he comprado el MiBand 3 solo para Hassio para device tracker y veo que no soy capaz de hacerlo.

**Comment by andrewjfreyer** [comment]
Creo que monitor.sh puede funcionar con MiBand, pero desafortunadamente no puedo verificarlo. Lo siento. Estoy trabajando para incorporar mas funciones en monitor.sh. Sera mas confiable que presense.sh.

Para errores de 'segmentation fault', use:
```
sudo apt-get update
sudo apt-get upgrade
```
Para probar su dispositivo MiBand, ejecute este comando:

`sudo hcitool lescan`

Ves el MiBand en los resultados?

**Comment by cgtobi** [comment]
Unpairing is not necessary and IMO actually counterproductive. Try pairing it but turn BT on the varied device off afterwards and test again. This is how it works with the Nokia Steel HR and the Chipolos.

**Comment by danielaradu2016** [comment]
andrewjfreyer . Buenas noche. Si lo veo . de aqui tengo el MAC. estoy haciendo un test con monitor.sh pero me da un fallo sobre el username de mqtt. es que yo tengo como username exactamente el mismo nombre ¨username¨ y contraseña otra. tengo `:`# ---------------------------
#
# MOSQUITTO PREFERENCES
#
# ---------------------------

# IP ADDRESS OF MQTT BROKER
mqtt_address="192.168.1.xx"

# MQTT BROKER USERNAME (OR BLANK FOR NONE)
mqtt_user="username"

# MQTT BROKER PASSWORD (OR BLANK FOR NONE)
mqtt_password="xxxxx"

# MQTT PUBLISH TOPIC ROOT
mqtt_topicpath="monitor"

# PUBLISHER IDENTITY
mqtt_publisher_identity="nickname"

# MQTT PORT
mqtt_port="1883"

# MQTT CERTIFICATE FILE
mqtt_certificate_path=''
``
and `# ---------------------------
#
# PUBLIC MAC ADDRESS LIST
#
# ---------------------------

EC:89:64:02:CC:54 Nickname #comment
`

**Comment by danielaradu2016** [comment]
sudo bash monitor.sh -t  
`Starting monitor.sh (v. 0.1.616)...
> trigger only mode enabled
Error: Please customize mqtt username in: mqtt_preferences

sudo bash monitor.sh -a
Starting monitor.sh (v. 0.1.616)...
> report all scan results mode enabled
Error: Please customize mqtt username in: mqtt_preferences

`

**Comment by danielaradu2016** [comment]
lo lamento muchisimo que te estoy molestando tanto.un saludo
y muchas gracias

**Comment by andrewjfreyer** [comment]
No hay problema! jaja. Entiendo ahora - el script no permite el nombre 'username' en las preferencias de mqtt, y eso es un error. Voy a arreglarlo. ademas, sugiero que cambies 'username' por seguridad...

Use optiones `-b` y `-g`

**Comment by andrewjfreyer** [comment]
@danielaradu2016 por favor abres una reporta en `monitor.sh` para continuar esta conversasion. Gracias!
