### ISSUE TITLE
Can topic name not using MAC? I can't let openhab read this info

### ISSUE THREAD

**Issue by hamwong** [andrewjfreyer/presence#21]
location/pi_zero_location/00:00:00:00:00:00 , as I think openhab not able to read topic name with:
in owner_devices, you set as "00:00:00:00:00:00 #My-Phone", can the mac address be assign on second part? My_Phone as below
location/pi_zero_location/My_Phone

**Comment by andrewjfreyer** [comment]
This is a feature of `monitor`, which is better suited for most purposes. There are no plans to implement in `presence`.
