### ISSUE TITLE
A Couple of Typos and Bluetooth Service Status

### ISSUE THREAD

**Issue by dennyfmn** [andrewjfreyer/presence#23]

**Comment by dennyfmn** [comment]
In the SD card setup section the ssh and wifi config files are in the /boot directory not /root.
In the Configure Presence section there are only 5 bytes of bluetooth MAC shown in the example, not 6.

When checking the bluetooth service status on my system there are errors/warning shown:

 sudo service bluetooth status

● bluetooth.service - Bluetooth service
   Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2018-12-01 12:56:28 CST; 6min ago
     Docs: man:bluetoothd(8)
 Main PID: 376 (bluetoothd)
   Status: "Running"
   CGroup: /system.slice/bluetooth.service
           └─376 /usr/lib/bluetooth/bluetoothd

Dec 01 12:56:27 raspberrypi systemd[1]: Starting Bluetooth service...
Dec 01 12:56:28 raspberrypi bluetoothd[376]: Bluetooth daemon 5.43
Dec 01 12:56:28 raspberrypi systemd[1]: Started Bluetooth service.
Dec 01 12:56:28 raspberrypi bluetoothd[376]: Starting SDP server
Dec 01 12:56:28 raspberrypi bluetoothd[376]: Bluetooth management interface 1.14 initialized
Dec 01 12:56:28 raspberrypi bluetoothd[376]: Failed to obtain handles for "Service Changed" characteristic
Dec 01 12:56:28 raspberrypi bluetoothd[376]: Sap driver initialization failed.
Dec 01 12:56:28 raspberrypi bluetoothd[376]: sap-server: Operation not permitted (1)
Dec 01 12:56:28 raspberrypi bluetoothd[376]: Failed to set privacy: Rejected (0x0b)

The Status is :"Running" and the presence service seems to work properly. I am getting MQTT messages on the broker.

Are these warnings anything to be concerned about?

Thanks for the great application! I had it up and running in about an hour.

**Comment by bpartridge83** [comment]
@dennyfmn Was there a resolution to those errors? I'm seeing the same thing with `sudo service bluetooth status`...
