### ISSUE TITLE
Installing new version of BlueZ

### ISSUE THREAD

**Issue by roshradha** [andrewjfreyer/presence#24]
I have a older version of Bluez running on my device. 
root@ubuntu:~# bluetoothd -v
5.37
How do I update this to a newer version.
I followed the instructions on how to install a new bluez version and then downloaded and installed bluez v 5.50.
But it seems that my system still uses older version of bluez. How do i delete the older version or specify to use new version?
I followed the steps of installation from:
https://learn.adafruit.com/install-bluez-on-the-raspberry-pi/installation

Note that I'm not using raspberry pi. I'm using linux inside a container.

**Comment by andrewjfreyer** [comment]
without more information about your container or distro, this question is beyond the scope of `presence` issue tracking. closing for now.
