### ISSUE TITLE
Installing pi-bluetooth forces reinstall of older bluez

### ISSUE THREAD

**Issue by airdrummingfool** [andrewjfreyer/presence#4]
Hello and thank you for this great project. I'm working on setting it up on an RPi3, but I'm having an issue related to installing the newer bluez version.

`make` works fine. Then I run `sudo make install`, which appears to complete without errors:
```
pi@MyPi:~/bluez-5.49 $ sudo make install
make --no-print-directory install-am
 /bin/mkdir -p '/usr/lib'
 /bin/bash ./libtool   --mode=install /usr/bin/install -c   lib/libbluetooth.la '/usr/lib'
libtool: install: /usr/bin/install -c lib/.libs/libbluetooth.so.3.18.16 /usr/lib/libbluetooth.so.3.18.16
libtool: install: (cd /usr/lib && { ln -s -f libbluetooth.so.3.18.16 libbluetooth.so.3 || { rm -f libbluetooth.so.3 && ln -s libbluetooth.so.3.18.16 libbluetooth.so.3; }; })
libtool: install: (cd /usr/lib && { ln -s -f libbluetooth.so.3.18.16 libbluetooth.so || { rm -f libbluetooth.so && ln -s libbluetooth.so.3.18.16 libbluetooth.so; }; })
libtool: install: /usr/bin/install -c lib/.libs/libbluetooth.lai /usr/lib/libbluetooth.la
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin" ldconfig -n /usr/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /usr/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /bin/mkdir -p '/usr/bin'
  /bin/bash ./libtool   --mode=install /usr/bin/install -c client/bluetoothctl monitor/btmon tools/rctest tools/l2test tools/l2ping tools/bccmd tools/bluemoon tools/hex2hcd tools/mpris-proxy tools/btattach '/usr/bin'
libtool: install: /usr/bin/install -c client/bluetoothctl /usr/bin/bluetoothctl
libtool: install: /usr/bin/install -c monitor/btmon /usr/bin/btmon
libtool: install: /usr/bin/install -c tools/rctest /usr/bin/rctest
libtool: install: /usr/bin/install -c tools/l2test /usr/bin/l2test
libtool: install: /usr/bin/install -c tools/l2ping /usr/bin/l2ping
libtool: install: /usr/bin/install -c tools/bccmd /usr/bin/bccmd
libtool: install: /usr/bin/install -c tools/bluemoon /usr/bin/bluemoon
libtool: install: /usr/bin/install -c tools/hex2hcd /usr/bin/hex2hcd
libtool: install: /usr/bin/install -c tools/mpris-proxy /usr/bin/mpris-proxy
libtool: install: /usr/bin/install -c tools/btattach /usr/bin/btattach
 /bin/mkdir -p '/usr/libexec/bluetooth'
  /bin/bash ./libtool   --mode=install /usr/bin/install -c src/bluetoothd obexd/src/obexd '/usr/libexec/bluetooth'
libtool: install: /usr/bin/install -c src/bluetoothd /usr/libexec/bluetooth/bluetoothd
libtool: install: /usr/bin/install -c obexd/src/obexd /usr/libexec/bluetooth/obexd
 /bin/mkdir -p '/usr/lib/cups/backend'
  /bin/bash ./libtool   --mode=install /usr/bin/install -c profiles/cups/bluetooth '/usr/lib/cups/backend'
libtool: install: /usr/bin/install -c profiles/cups/bluetooth /usr/lib/cups/backend/bluetooth
 /bin/mkdir -p '/etc/dbus-1/system.d'
 /usr/bin/install -c -m 644 src/bluetooth.conf '/etc/dbus-1/system.d'
 /bin/mkdir -p '/usr/include/bluetooth'
 /usr/bin/install -c -m 644 lib/bluetooth.h lib/hci.h lib/hci_lib.h lib/sco.h lib/l2cap.h lib/sdp.h lib/sdp_lib.h lib/rfcomm.h lib/bnep.h lib/cmtp.h lib/hidp.h '/usr/include/bluetooth'
 /bin/mkdir -p '/usr/share/man/man1'
 /usr/bin/install -c -m 644 tools/rctest.1 tools/l2ping.1 tools/bccmd.1 tools/btattach.1 tools/hid2hci.1 '/usr/share/man/man1'
 /bin/mkdir -p '/usr/share/man/man8'
 /usr/bin/install -c -m 644 src/bluetoothd.8 '/usr/share/man/man8'
 /bin/mkdir -p '/usr/lib/pkgconfig'
 /usr/bin/install -c -m 644 lib/bluez.pc '/usr/lib/pkgconfig'
 /bin/mkdir -p '/lib/udev/rules.d'
 /usr/bin/install -c -m 644 tools/97-hid2hci.rules '/lib/udev/rules.d'
 /bin/mkdir -p '/lib/udev'
  /bin/bash ./libtool   --mode=install /usr/bin/install -c tools/hid2hci '/lib/udev'
libtool: install: /usr/bin/install -c tools/hid2hci /lib/udev/hid2hci
```
Then I run `sudo apt-get update` and `sudo apt-get upgrade -y`, which doesn't install or update anything.

There's no `bluetoothd` in my path at this point, but it does exist in `src/bluetoothd`:
```
pi@MyPi:~/bluez-5.49 $ which bluetoothd
pi@MyPi:~/bluez-5.49 $ bluetoothd -v
-bash: bluetoothd: command not found
pi@MyPi:~/bluez-5.49 $ src/bluetoothd -v
5.49
```

Then I run `sudo apt-get install pi-bluetooth`, but instead of being given the option to skip bluez installation during setup, an older version of bluez (5.43) is forced on me (only one file conflicts):
```
pi@MyPi:~ $ sudo apt-get install pi-bluetooth
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  bluez
Suggested packages:
  pulseaudio-module-bluetooth
The following NEW packages will be installed:
  bluez pi-bluetooth
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/725 kB of archives.
After this operation, 3,467 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Selecting previously unselected package bluez.
(Reading database ... 73012 files and directories currently installed.)
Preparing to unpack .../bluez_5.43-2+rpt2+deb9u2_armhf.deb ...
Unpacking bluez (5.43-2+rpt2+deb9u2) ...
Selecting previously unselected package pi-bluetooth.
Preparing to unpack .../pi-bluetooth_0.1.7_all.deb ...
Unpacking pi-bluetooth (0.1.7) ...
Processing triggers for systemd (232-25+deb9u2) ...
Processing triggers for man-db (2.7.6.1-2) ...
Processing triggers for dbus (1.10.26-0+deb9u1) ...
Setting up bluez (5.43-2+rpt2+deb9u2) ...

Configuration file '/etc/dbus-1/system.d/bluetooth.conf'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** bluetooth.conf (Y/I/N/O/D/Z) [default=N] ? n
Created symlink /etc/systemd/system/dbus-org.bluez.service → /lib/systemd/system/bluetooth.service.
Created symlink /etc/systemd/system/bluetooth.target.wants/bluetooth.service → /lib/systemd/system/bluetooth.service.
Setting up pi-bluetooth (0.1.7) ...
Created symlink /etc/systemd/system/multi-user.target.wants/hciuart.service → /lib/systemd/system/hciuart.service.
Processing triggers for dbus (1.10.26-0+deb9u1) ...
Processing triggers for systemd (232-25+deb9u2) ...
```

Once I go through with installation and allow `sudo apt-get install pi-bluetooth` to install bluez, I end up with an older version of bluez:
```
pi@MyPi:~ $ bluetoothd -v
5.43
```

I saw [one other mention](https://community.home-assistant.io/t/reliable-multi-user-distributed-bluetooth-occupancy-presence-detection/50674/77) of a similar issue in the HA discussion forum, but they were able to resolve it by trying again. I've run through the steps 3 times now with the same result each time.

I've tried rebooting, running `make` multiple times, `sudo make install` multiple times, etc. Do you have any suggestions on things to try? I'm hoping I'm doing something dumb... In the meantime I will continue with the older version of bluez.

Thanks again!

**Comment by PianSom** [comment]
IIRC you need to say "y" to `sudo apt-get install pi-bluetooth`. Then after it starts it asks if you want to overwrite the bluez you have installed, to which you should answer "n"

**Comment by airdrummingfool** [comment]
@PianSom thanks for your reply! Unfortunately, I am not given the option to overwrite an existing bluez installation - once I say "y" to start, installation chugs right through setting up the older version of bluez (except for one configuration file conflict). I've updated my initial issue to show what happens when I accept installation instead of denying it.

It seems like my compiled version of bluez may not be getting fully "installed". After running `make install`, the `bluetooth` service does not exist, and `bluetoothd` is not in the system PATH (but it is compiled locally). Note that this is after running `sudo make install`.
```
pi@MyPi:~/bluez-5.49 $ sudo service bluetooth start
Failed to start bluetooth.service: Unit bluetooth.service not found.
pi@MyPi:~/bluez-5.49 $ which bluetoothd
pi@MyPi:~/bluez-5.49 $ bluetoothd -v
-bash: bluetoothd: command not found
pi@MyPi:~/bluez-5.49 $ src/bluetoothd -v
5.49
```

**Comment by PianSom** [comment]
I think you have edited your query since I responded? I was referring to the section marked 
````
Setting up bluez (5.43-2+rpt2+deb9u2) ...

Configuration file '/etc/dbus-1/system.d/bluetooth.conf'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** bluetooth.conf (Y/I/N/O/D/Z) [default=N] ? n
````
in your post as it now is above.

So you were given the option and - correctly - you did not overwrite the existing bluez installation. What went wrong from there?

Guilty confession time - the first time I followed Andrew's instructions I didn't spend enough time looking at the folder and installed version 5.4 on my Pi 3. It worked just fine. So I doubt that 5.43 would cause any issue, in any case.  

I am now very confused about what you have run when. Why did you run `sudo apt-get install pi-bluetooth bluez-`? My best suggestion is that you start at the top of Andrew's Step 4 (with a removal of bluez; possibly doing a reboot and an update afterwards to try and make sure you have cleaned up) and post back here with any issues that come up from there. Just make sure you follow the instructions.

**Comment by airdrummingfool** [comment]
@PianSom I apologize for the confusion.

Yes, I edited my post after your first reply because I realized what I had originally (me rejecting the `pi-bluetooth` installation) didn't make much sense to include. I now see that `sudo apt-get install pi-bluetooth bluez-` also doesn't make much sense in context - I only included that because I wanted to show I had tried to figure this out on my own. I've edited my post again, and hopefully now it makes sense. For clarity's sake, although I did a terrible job of showing it, I did follow the instructions straight through.


> So you were given the option and - correctly - you did not overwrite the existing bluez installation. 

Are you suggesting that by declining to update `/etc/dbus-1/system.d/bluetooth.conf` during the installation, I am preserving my compiled version of bluez? That file appears to be "security policies" only, and it is almost identical to the one present in version 5.43. Plus, after installation completes the output of `bluetoothd -v` is `5.43`, when I would expect `5.49` if I had correctly preserved the compiled version.

It's worth noting that I have been running `5.43` for two days now, and BT presence has been working fantastically. So this isn't a critical issue by any means, though I am curious about where I went wrong.

**Comment by andrewjfreyer** [comment]
@airdrummingfool Thanks for the report. The recommendation to install the latest bluez was more relevant months ago before pi-bluetooth was updated recently. You'll be fine with 5.43. 

I'll edit the readme a bit, since the installation of the most modern bluez is not an express requirement. 

Closing.

**Comment by airdrummingfool** [comment]
@andrewjfreyer Ah, I see. Thank you!

**Comment by balk77** [comment]
@andrewjfreyer 
> I'll edit the readme a bit, since the installation of the most modern bluez is not an express requirement.

I also noticed that when doing a manual installation of BlueZ, `hcitool` is no longer installed. So, if the shipped version works fine, maybe remove it from the manual?
