### ISSUE TITLE
Last Will not working as expected

### ISSUE THREAD

**Issue by andrewjfreyer** [andrewjfreyer/presence#5]
### Description

Last will messages not sending from broker when presence service is stopped.

**Comment by airdrummingfool** [comment]
I don't think this is possible with the current usage of `mosquitto_pub`.

From [a mailing list thread](https://dev.eclipse.org/mhonarc/lists/mosquitto-dev/msg00897.html):

> You are passing the payload on the command line (-m) and _pub will close
and finish correctly when it's sent that out.
> 
> Try a longer-lived _pub with, say, -l which reads from stdin; if you
kill mosquitto_pub it ought to publish the LWT.

**Comment by andrewjfreyer** [comment]
@airdrummingfool - you're completely right about the **mosquitto_pub**; we'd need to keep the connection option. 

... however, I do have a good solution that I'll be releasing soon! It does not involve **mosquitto_pub**, but instead **mosquitto_sub**.
